"""Data models for Instagram content briefs and shot specifications.

These models define the content planning and generation pipeline inputs.
Includes video content format taxonomy and video intent models.
"""

import dataclasses
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from ..utils.hashing import canonical_hash


class ContentFormat(str, Enum):
    """Determines the video generation path. Each format routes to a different
    Kling endpoint and requires different inputs."""

    STATIC_IMAGE = "static_image"
    AVATAR_TALKING = "avatar_talking"
    NARRATIVE_REEL = "narrative_reel"
    CINEMATIC_CLIP = "cinematic_clip"
    GAMEPLAY_OVERLAY = "gameplay_overlay"


class ContentFormatWeights:
    """Weekly content mix weights. Adjusted by day-of-week in calendar.py."""

    def __init__(
        self,
        static_image: float = 0.25,
        avatar_talking: float = 0.30,
        narrative_reel: float = 0.20,
        cinematic_clip: float = 0.15,
        gameplay_overlay: float = 0.10,
    ):
        self.static_image = static_image
        self.avatar_talking = avatar_talking
        self.narrative_reel = narrative_reel
        self.cinematic_clip = cinematic_clip
        self.gameplay_overlay = gameplay_overlay

    def to_dict(self) -> dict[str, float]:
        return {
            "static_image": self.static_image,
            "avatar_talking": self.avatar_talking,
            "narrative_reel": self.narrative_reel,
            "cinematic_clip": self.cinematic_clip,
            "gameplay_overlay": self.gameplay_overlay,
        }

    def normalized(self) -> dict[str, float]:
        """Return weights normalized to sum to 1.0."""
        values = self.to_dict()
        total = sum(values.values())
        if total == 0:
            return values
        return {k: v / total for k, v in values.items()}


@dataclass(frozen=True)
class InstagramContentBrief:
    """
    The starting point of every content generation run.

    Equivalent to the blog topic selection, but expanded for Instagram's
    format variety and engagement mechanics. This is generated by the
    ContentCalendar and then elaborated by the IntentBuilder.
    """
    character_id: str                   # Must exist in CharacterRegistry
    content_pillar: str                 # "lifestyle" | "travel" | "fashion" | "food"
                                        # | "wellness" | "behind_scenes" | "personal_moment"
    post_format: str                    # "single_image" | "carousel" | "reel"
    narrative_hook: str                 # The emotional/story hook for this post.
                                        # e.g., "quiet morning routine before a busy day"
    scene_description: str              # Natural language scene setup for the LLM.
                                        # e.g., "A peaceful apartment kitchen, early morning,
                                        #         coffee being made, golden light from window"
                                        # (Filled in by IntentBuilder if empty)
    tone: str                           # "intimate" | "aspirational" | "playful"
                                        # | "reflective" | "spontaneous"
    target_emotion: str                 # What should the viewer FEEL?
                                        # e.g., "cozy and slightly envious in a pleasant way"
    caption_style: str                  # "short_punchy" | "storytelling" | "question"
                                        # | "minimal" | "relatable_commentary"
    hashtag_strategy: str               # "niche" | "broad" | "mixed" | "none"
    platform_target: str                # "instagram_feed" | "instagram_reels"
    content_format: ContentFormat = ContentFormat.STATIC_IMAGE  # Video generation path
    scheduled_post_time: Optional[str] = None  # ISO datetime, None = ASAP
    brief_hash: Optional[str] = None    # Set after construction, before pipeline runs

    def with_hash(self) -> "InstagramContentBrief":
        """Return a copy of this brief with computed brief_hash."""
        data = dataclasses.asdict(self)
        data["brief_hash"] = None  # Exclude hash from its own computation
        return dataclasses.replace(self, brief_hash=canonical_hash(data))


@dataclass(frozen=True)
class ShotSpec:
    """
    A fully specified single image to generate.

    The generation prompt is assembled FROM this spec — it is never
    written by hand. This is the structural clarity principle from the
    video pipeline plan, applied to still images.
    """
    shot_index: int
    character_id: str
    scene: str                  # Environment description
    action: str                 # What is the character doing?
    expression: str             # Precise facial expression
    framing: str                # "portrait_tight" | "portrait_medium" | "half_body"
                                # | "full_body" | "over_shoulder" | "environmental"
    camera_angle: str           # "eye_level" | "slightly_above" | "slightly_below"
                                # | "dutch_tilt" | "pov"
    lighting: str               # From StyleDNA.lighting_preference
    wardrobe: str               # From StyleDNA.wardrobe_style + scene context
    background_detail: str      # Specific background elements
    is_hero_shot: bool = False  # True for the primary image in a carousel
    duration: int = 5            # Duration in seconds (for video shots)
    camera: str = ""             # Camera movement, e.g. "tracking shot, eye level"
    shot_size: str = ""          # e.g. "medium", "close-up", "wide"
    transition_from_prev: str = ""  # e.g. "cut", "crossfade"
    shot_hash: Optional[str] = None
    pose_category: Optional[str] = None  # OpenPose category for ControlNet body positioning

    def with_hash(self) -> "ShotSpec":
        """Return a copy of this shot spec with computed shot_hash."""
        data = dataclasses.asdict(self)
        data["shot_hash"] = None
        return dataclasses.replace(self, shot_hash=canonical_hash(data))

    def build_generation_prompt(
        self,
        identity_anchor: "IdentityAnchor",  # type: ignore
        style_dna: "StyleDNA",  # type: ignore
        lora_trigger_word: str,
        style_addendum: str = "",
    ) -> str:
        """
        Assemble the final generation prompt from structured fields.

        No creative writing — pure composition. Same principle as
        build_generation_prompt() in the video pipeline plan.

        Args:
            identity_anchor: Character's visual identity
            style_dna: Character's aesthetic style
            lora_trigger_word: LoRA trigger word (e.g., "AURORA_V1")
            style_addendum: Optional additional style instructions

        Returns:
            Complete generation prompt string
        """
        return (
            f"{lora_trigger_word} person, {identity_anchor.face_description}, "
            f"{identity_anchor.hair_description}, {identity_anchor.skin_description}. "
            f"{self.action} in {self.scene}. "
            f"Expression: {self.expression}. "
            f"{self.framing} shot, {self.camera_angle} angle. "
            f"Wearing: {self.wardrobe}. "
            f"Background: {self.background_detail}. "
            f"Lighting: {self.lighting}. "
            f"Photography style: {style_dna.photography_style}, "
            f"{style_dna.color_palette}. "
            f"Photorealistic, not AI-generated looking, candid feel. "
            f"{style_addendum}"
        ).strip()


@dataclass
class PostIntent:
    """
    Fully elaborated post specification after LLM expansion.

    This is the output of IntentBuilder (Stage 2) and the input to
    asset generation (Stage 3).

    Not frozen because it's built incrementally during Stage 2.
    """
    brief: InstagramContentBrief
    elaborated_scene: str               # Full scene description, 2-3 sentences
    time_of_day: str                    # "morning" | "afternoon" | "golden_hour" | "night"
    weather_mood: str                   # "bright_sunny" | "overcast" | "cloudy_dramatic" | "interior_warmth"
    character_pose: str                 # Specific body pose — be precise
    character_expression: str           # Specific facial expression — be precise
    wardrobe_detail: str                # What she's wearing, consistent with StyleDNA
    shot_specs: list[ShotSpec] = field(default_factory=list)  # One per image
    caption_draft: str = ""             # First draft caption
    caption_alt_variants: list[str] = field(default_factory=list)  # 2 alternative options
    hashtag_set: list[str] = field(default_factory=list)  # 8-15 hashtags
    emotional_cta: str = ""             # What implicit call-to-action does the post create?
    ai_disclosure_text: str = "AI-generated content"  # Required disclosure
    intent_hash: Optional[str] = None   # Computed after full construction

    def with_hash(self) -> "PostIntent":
        """Compute and return intent_hash."""
        data = dataclasses.asdict(self)
        data["intent_hash"] = None
        self.intent_hash = canonical_hash(data)
        return self


@dataclass
class VideoIntent:
    """Extended intent for video content. Passed to VideoProviderRegistry."""

    content_format: ContentFormat
    prompt: str
    shot_list: list[ShotSpec] = field(default_factory=list)
    character_refs: list[str] = field(default_factory=list)  # Image URLs
    audio_url: Optional[str] = None
    source_video_url: Optional[str] = None  # For gameplay_overlay
    duration: int = 5  # seconds per clip
    aspect_ratio: str = "9:16"  # Instagram default
    native_audio: bool = True  # Kling audio generation
    voice_ids: list[str] = field(default_factory=list)  # Kling voice references
    cfg_scale: float = 0.5  # Prompt adherence
    caption_draft: str = ""
    hashtag_set: list[str] = field(default_factory=list)
    character_id: str = ""
    brief_hash: Optional[str] = None
    intent_hash: Optional[str] = None

    def with_hash(self) -> "VideoIntent":
        """Compute and return intent_hash."""
        data = dataclasses.asdict(self)
        data["intent_hash"] = None
        self.intent_hash = canonical_hash(data)
        return self
